envVarGroups:
  - name: fxql-parser-service

databases:
  - name: fxql-parser-service-postgres
    plan: free

services:
  - type: web
    name: fxql-parser-service
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: fxql-parser-service-postgres
          property: connectionString